// Auto-generated Audio Asset Map (do not edit by hand - run: npm run generate:audio)
export const audioMap = {
  "Welcome to Comparing Percentages! Ready to compare percents and find out who really wins? Let's roll!": "/assets/audio/home_intro.mp3",
  "key:home_intro": "/assets/audio/home_intro.mp3",
  "Robo scored 18 out of 20 on Quiz A. Alex scored 40 out of 50 on Quiz B. Alex says: I got 40 points and Robo got only 18, so my score is better. Bigger number, bigger score! Is that actually true? Remember, to compare fairly, turn every score into a percent, a number out of 100!": "/assets/audio/wonder_prompt.mp3",
  "key:wonder_prompt": "/assets/audio/wonder_prompt.mp3",
  "What if we put both scores on the same 100 point ruler? Who would be ahead then?": "/assets/audio/wonder_teaser.mp3",
  "key:wonder_teaser": "/assets/audio/wonder_teaser.mp3",
  "The word percent means out of 100! Picture a grid of 100 little squares. If 45 squares are shaded, that is 45%, which is 45 out of 100. As a fraction it is 45/100, and as a decimal it is 0.45. Fractions, decimals, and percents are three names for the same amount!": "/assets/audio/story_slide_1.mp3",
  "key:story_slide_1": "/assets/audio/story_slide_1.mp3",
  "When two percents are taken of the same whole, the bigger percent is the bigger share. To compare a fraction, a decimal, and a percent, change them all into percents first. 3/5 is 60% and 0.65 is 65%, so 0.65 is greater than 3/5!": "/assets/audio/story_slide_2.mp3",
  "key:story_slide_2": "/assets/audio/story_slide_2.mp3",
  "A bigger percent does not always mean a bigger amount! Compare 50% of 20 apples with 30% of 80 apples. Half of 20 is 10, but 30% of 80 is 24. The smaller percent gave more, because its whole was much bigger. Always ask: percent of what?": "/assets/audio/story_slide_3.mp3",
  "key:story_slide_3": "/assets/audio/story_slide_3.mp3",
  "Detective Time! Shop A gives 20% off an $80 jacket. Shop B gives 30% off a $50 bag. Shop A saves 20% of 80, which is $16. Shop B saves 30% of 50, which is $15. The smaller discount saved more money! Shop A saves more, even though Shop B has the bigger percent!": "/assets/audio/story_slide_4.mp3",
  "key:story_slide_4": "/assets/audio/story_slide_4.mp3",
  "Welcome to the Percent Grid Lab! Drag across each grid to shade squares. Watch the percent update live and see which grid is greater. Then switch on real amounts to discover why the whole matters!": "/assets/audio/station_a_intro.mp3",
  "key:station_a_intro": "/assets/audio/station_a_intro.mp3",
  "Time for the Percent Sorter! Tap the cards from smallest to largest. Fractions, decimals, and percents are all mixed up, so change each one into a percent to sort them fairly!": "/assets/audio/station_b_intro.mp3",
  "key:station_b_intro": "/assets/audio/station_b_intro.mp3",
  "Welcome, Detective! Two shops are having a sale. Work out how much money each shop saves you, then crack the case: which deal is really better?": "/assets/audio/station_c_intro.mp3",
  "key:station_c_intro": "/assets/audio/station_c_intro.mp3",
  "Welcome to the Real-World Percent Lab! Try quiz scores, basketball shots, phone batteries, and game downloads. Change the scores and totals, and see who is really ahead on the same 100 percent ruler!": "/assets/audio/station_d_intro.mp3",
  "key:station_d_intro": "/assets/audio/station_d_intro.mp3",
  "Choose your world on the map! Beat each world to unlock the next. Earn stars and XP!": "/assets/audio/practice_welcome.mp3",
  "key:practice_welcome": "/assets/audio/practice_welcome.mp3",
  "Awesome job! You got it right!": "/assets/audio/correct_cheer.mp3",
  "key:correct_cheer": "/assets/audio/correct_cheer.mp3",
  "Not quite. Remember, to compare fairly, turn everything into a percent, out of 100!": "/assets/audio/incorrect_try_again.mp3",
  "key:incorrect_try_again": "/assets/audio/incorrect_try_again.mp3",
  "Oh no! Out of hearts! Don't worry, try again to master this world!": "/assets/audio/out_of_hearts.mp3",
  "key:out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "Congratulations! You completed the world and earned new stars!": "/assets/audio/world_complete.mp3",
  "key:world_complete": "/assets/audio/world_complete.mp3",
  "Amazing work! Let's reflect on what you learned.": "/assets/audio/reflect_intro.mp3",
  "key:reflect_intro": "/assets/audio/reflect_intro.mp3",
  "What does the word percent mean?": "/assets/audio/reflect_q1.mp3",
  "key:reflect_q1": "/assets/audio/reflect_q1.mp3",
  "Percent means out of 100! So 45% is 45 out of 100, which is the fraction 45/100 or the decimal 0.45.": "/assets/audio/reflect_a1.mp3",
  "key:reflect_a1": "/assets/audio/reflect_a1.mp3",
  "How do you compare a fraction, a decimal, and a percent?": "/assets/audio/reflect_q2.mp3",
  "key:reflect_q2": "/assets/audio/reflect_q2.mp3",
  "Change them all into percents first. Then the biggest percent is the greatest value!": "/assets/audio/reflect_a2.mp3",
  "key:reflect_a2": "/assets/audio/reflect_a2.mp3",
  "How do you change a fraction into a percent?": "/assets/audio/reflect_q3.mp3",
  "key:reflect_q3": "/assets/audio/reflect_q3.mp3",
  "Make the bottom number 100, or divide the top by the bottom and multiply by 100. For example, 3/5 is 60/100, which is 60%!": "/assets/audio/reflect_a3.mp3",
  "key:reflect_a3": "/assets/audio/reflect_a3.mp3",
  "Does a bigger percent always mean a bigger amount?": "/assets/audio/reflect_q4.mp3",
  "key:reflect_q4": "/assets/audio/reflect_q4.mp3",
  "No! Always find the amount for each one. 30% of 80 is 24, which is more than 50% of 20, which is only 10.": "/assets/audio/reflect_a4.mp3",
  "key:reflect_a4": "/assets/audio/reflect_a4.mp3",
  "How do you compare two scores that have different totals?": "/assets/audio/reflect_q5.mp3",
  "key:reflect_q5": "/assets/audio/reflect_q5.mp3",
  "Turn each score into a percent. 18 out of 20 is 90%, and 40 out of 50 is 80%, so 18 out of 20 is the better score!": "/assets/audio/reflect_a5.mp3",
  "key:reflect_a5": "/assets/audio/reflect_a5.mp3",
  "What is the difference between percentage points and percent change?": "/assets/audio/reflect_q6.mp3",
  "key:reflect_q6": "/assets/audio/reflect_q6.mp3",
  "Percentage points are the gap between two percents. Going from 40% to 50% is 10 percentage points, but it is a 25% increase, because 10 is a quarter of 40!": "/assets/audio/reflect_a6.mp3",
  "key:reflect_a6": "/assets/audio/reflect_a6.mp3",
  "A grid has 100 squares. 35 squares are shaded. What percent of the grid is shaded?": "/assets/audio/w1_q1_prompt.mp3",
  "key:w1_q1_prompt": "/assets/audio/w1_q1_prompt.mp3",
  "Percent means out of 100. Count the shaded squares out of the 100 squares.": "/assets/audio/w1_q1_hint.mp3",
  "key:w1_q1_hint": "/assets/audio/w1_q1_hint.mp3",
  "What percent of this 100-square grid is shaded?": "/assets/audio/w1_q2_prompt.mp3",
  "key:w1_q2_prompt": "/assets/audio/w1_q2_prompt.mp3",
  "key:w1_q2_hint": "/assets/audio/w1_q1_hint.mp3",
  "Only 8 squares out of 100 are shaded. What percent is shaded?": "/assets/audio/w1_q3_prompt.mp3",
  "key:w1_q3_prompt": "/assets/audio/w1_q3_prompt.mp3",
  "key:w1_q3_hint": "/assets/audio/w1_q1_hint.mp3",
  "In this grid, 47 of the 100 squares are shaded. What percent is NOT shaded?": "/assets/audio/w1_q4_prompt.mp3",
  "key:w1_q4_prompt": "/assets/audio/w1_q4_prompt.mp3",
  "The whole grid is 100%. Subtract the shaded percent from 100%.": "/assets/audio/w1_q4_hint.mp3",
  "key:w1_q4_hint": "/assets/audio/w1_q4_hint.mp3",
  "What percent of the grid is shaded?": "/assets/audio/w1_q5_prompt.mp3",
  "key:w1_q5_prompt": "/assets/audio/w1_q5_prompt.mp3",
  "key:w1_q5_hint": "/assets/audio/w1_q1_hint.mp3",
  "23 out of 100 squares are shaded. Write this as a percent.": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q6_prompt": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q6_hint": "/assets/audio/w1_q1_hint.mp3",
  "91 of the 100 squares are shaded. What percent of the squares are NOT shaded?": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_prompt": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_hint": "/assets/audio/w1_q4_hint.mp3",
  "Out of 100 students, 64 walk to school. What percent of the students walk?": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q8_prompt": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q8_hint": "/assets/audio/w1_q1_hint.mp3",
  "What percent of the 100-square grid is shaded?": "/assets/audio/w1_q9_prompt.mp3",
  "key:w1_q9_prompt": "/assets/audio/w1_q9_prompt.mp3",
  "key:w1_q9_hint": "/assets/audio/w1_q1_hint.mp3",
  "A grid has 70 of its 100 squares shaded. What percent is shaded?": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_prompt": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_hint": "/assets/audio/w1_q1_hint.mp3",
  "Write the fraction 3/4 as a percent.": "/assets/audio/w2_q1_prompt.mp3",
  "key:w2_q1_prompt": "/assets/audio/w2_q1_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 25.": "/assets/audio/w2_q1_hint.mp3",
  "key:w2_q1_hint": "/assets/audio/w2_q1_hint.mp3",
  "A recipe uses 2/5 of a bag of flour. What percent of the bag is that?": "/assets/audio/w2_q2_prompt.mp3",
  "key:w2_q2_prompt": "/assets/audio/w2_q2_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 20.": "/assets/audio/w2_q2_hint.mp3",
  "key:w2_q2_hint": "/assets/audio/w2_q2_hint.mp3",
  "Write 7/10 as a percent.": "/assets/audio/w2_q3_prompt.mp3",
  "key:w2_q3_prompt": "/assets/audio/w2_q3_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 10.": "/assets/audio/w2_q3_hint.mp3",
  "key:w2_q3_hint": "/assets/audio/w2_q3_hint.mp3",
  "Robo finished 9/20 of a race. What percent of the race is that?": "/assets/audio/w2_q4_prompt.mp3",
  "key:w2_q4_prompt": "/assets/audio/w2_q4_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 5.": "/assets/audio/w2_q4_hint.mp3",
  "key:w2_q4_hint": "/assets/audio/w2_q4_hint.mp3",
  "Write the fraction 13/25 as a percent.": "/assets/audio/w2_q5_prompt.mp3",
  "key:w2_q5_prompt": "/assets/audio/w2_q5_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 4.": "/assets/audio/w2_q5_hint.mp3",
  "key:w2_q5_hint": "/assets/audio/w2_q5_hint.mp3",
  "17/50 of the class plays chess. What percent of the class is that?": "/assets/audio/w2_q6_prompt.mp3",
  "key:w2_q6_prompt": "/assets/audio/w2_q6_prompt.mp3",
  "Make the bottom number 100. Multiply the top and bottom by 2.": "/assets/audio/w2_q6_hint.mp3",
  "key:w2_q6_hint": "/assets/audio/w2_q6_hint.mp3",
  "Write 3/20 as a percent.": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_prompt": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_hint": "/assets/audio/w2_q4_hint.mp3",
  "A phone battery is 21/25 full. What percent full is it?": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_prompt": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_hint": "/assets/audio/w2_q5_hint.mp3",
  "Write 4/5 as a percent.": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_prompt": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_hint": "/assets/audio/w2_q2_hint.mp3",
  "Alex read 11/20 of a book. What percent of the book has Alex read?": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_prompt": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_hint": "/assets/audio/w2_q4_hint.mp3",
  "Write the decimal 0.35 as a percent.": "/assets/audio/w3_q1_prompt.mp3",
  "key:w3_q1_prompt": "/assets/audio/w3_q1_prompt.mp3",
  "To change a decimal to a percent, multiply by 100. That moves the decimal point two places to the right.": "/assets/audio/w3_q1_hint.mp3",
  "key:w3_q1_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write 72% as a decimal.": "/assets/audio/w3_q2_prompt.mp3",
  "key:w3_q2_prompt": "/assets/audio/w3_q2_prompt.mp3",
  "To change a percent to a decimal, divide by 100. That moves the decimal point two places to the left.": "/assets/audio/w3_q2_hint.mp3",
  "key:w3_q2_hint": "/assets/audio/w3_q2_hint.mp3",
  "Write the decimal 0.07 as a percent.": "/assets/audio/w3_q3_prompt.mp3",
  "key:w3_q3_prompt": "/assets/audio/w3_q3_prompt.mp3",
  "key:w3_q3_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write the decimal 0.6 as a percent.": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_prompt": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write 4% as a decimal.": "/assets/audio/w3_q5_prompt.mp3",
  "key:w3_q5_prompt": "/assets/audio/w3_q5_prompt.mp3",
  "key:w3_q5_hint": "/assets/audio/w3_q2_hint.mp3",
  "Robo grew a plant to 1.2 times its old height. Write 1.2 as a percent.": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_prompt": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write 45% as a decimal.": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q7_prompt": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q7_hint": "/assets/audio/w3_q2_hint.mp3",
  "Write the decimal 0.9 as a percent.": "/assets/audio/w3_q8_prompt.mp3",
  "key:w3_q8_prompt": "/assets/audio/w3_q8_prompt.mp3",
  "key:w3_q8_hint": "/assets/audio/w3_q1_hint.mp3",
  "Write 150% as a decimal.": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q9_prompt": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q9_hint": "/assets/audio/w3_q2_hint.mp3",
  "Write the decimal 0.08 as a percent.": "/assets/audio/w3_q10_prompt.mp3",
  "key:w3_q10_prompt": "/assets/audio/w3_q10_prompt.mp3",
  "key:w3_q10_hint": "/assets/audio/w3_q1_hint.mp3",
  "Which is greater: 3/5 or 65%?": "/assets/audio/w4_q1_prompt.mp3",
  "key:w4_q1_prompt": "/assets/audio/w4_q1_prompt.mp3",
  "Change both values to percents first. For example, 3/5 = 60%.": "/assets/audio/w4_q1_hint.mp3",
  "key:w4_q1_hint": "/assets/audio/w4_q1_hint.mp3",
  "Which is smaller: 0.42 or 40%?": "/assets/audio/w4_q2_prompt.mp3",
  "key:w4_q2_prompt": "/assets/audio/w4_q2_prompt.mp3",
  "Change both values to percents first. For example, 0.42 = 42%.": "/assets/audio/w4_q2_hint.mp3",
  "key:w4_q2_hint": "/assets/audio/w4_q2_hint.mp3",
  "Which is greater: 7/20 or 0.4?": "/assets/audio/w4_q3_prompt.mp3",
  "key:w4_q3_prompt": "/assets/audio/w4_q3_prompt.mp3",
  "Change both values to percents first. For example, 7/20 = 35%.": "/assets/audio/w4_q3_hint.mp3",
  "key:w4_q3_hint": "/assets/audio/w4_q3_hint.mp3",
  "Which is greater: 9/20 or 45%?": "/assets/audio/w4_q4_prompt.mp3",
  "key:w4_q4_prompt": "/assets/audio/w4_q4_prompt.mp3",
  "Change both values to percents first. For example, 9/20 = 45%.": "/assets/audio/w4_q4_hint.mp3",
  "key:w4_q4_hint": "/assets/audio/w4_q4_hint.mp3",
  "Which is greater: 5/8 or 0.6?": "/assets/audio/w4_q5_prompt.mp3",
  "key:w4_q5_prompt": "/assets/audio/w4_q5_prompt.mp3",
  "Change both values to percents first. For example, 5/8 = 62.5%.": "/assets/audio/w4_q5_hint.mp3",
  "key:w4_q5_hint": "/assets/audio/w4_q5_hint.mp3",
  "Which is smaller: 0.3 or 3/8?": "/assets/audio/w4_q6_prompt.mp3",
  "key:w4_q6_prompt": "/assets/audio/w4_q6_prompt.mp3",
  "Change both values to percents first. For example, 0.3 = 30%.": "/assets/audio/w4_q6_hint.mp3",
  "key:w4_q6_hint": "/assets/audio/w4_q6_hint.mp3",
  "Which is greater: 0.7 or 3/4?": "/assets/audio/w4_q7_prompt.mp3",
  "key:w4_q7_prompt": "/assets/audio/w4_q7_prompt.mp3",
  "Change both values to percents first. For example, 0.7 = 70%.": "/assets/audio/w4_q7_hint.mp3",
  "key:w4_q7_hint": "/assets/audio/w4_q7_hint.mp3",
  "Which is smaller: 58% or 0.6?": "/assets/audio/w4_q8_prompt.mp3",
  "key:w4_q8_prompt": "/assets/audio/w4_q8_prompt.mp3",
  "Change both values to percents first. For example, 0.6 = 60%.": "/assets/audio/w4_q8_hint.mp3",
  "key:w4_q8_hint": "/assets/audio/w4_q8_hint.mp3",
  "Which is greater: 2/3 or 65%?": "/assets/audio/w4_q9_prompt.mp3",
  "key:w4_q9_prompt": "/assets/audio/w4_q9_prompt.mp3",
  "Change both values to percents first. For example, 2/3 = about 66.7%.": "/assets/audio/w4_q9_hint.mp3",
  "key:w4_q9_hint": "/assets/audio/w4_q9_hint.mp3",
  "Which is greater: 13/25 or 0.5?": "/assets/audio/w4_q10_prompt.mp3",
  "key:w4_q10_prompt": "/assets/audio/w4_q10_prompt.mp3",
  "Change both values to percents first. For example, 13/25 = 52%.": "/assets/audio/w4_q10_hint.mp3",
  "key:w4_q10_hint": "/assets/audio/w4_q10_hint.mp3",
  "Which value is the greatest?": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q1_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "Change every value into a percent, then line them up from smallest to largest.": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q1_hint": "/assets/audio/w5_q1_hint.mp3",
  "Which value is the smallest?": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_hint": "/assets/audio/w5_q1_hint.mp3",
  "Which value is the second greatest?": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_prompt": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q4_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q4_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q5_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q5_hint": "/assets/audio/w5_q1_hint.mp3",
  "Which value is the second smallest?": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_prompt": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q7_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q7_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q8_prompt": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q8_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q9_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q9_hint": "/assets/audio/w5_q1_hint.mp3",
  "key:w5_q10_prompt": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q10_hint": "/assets/audio/w5_q1_hint.mp3",
  "Robo scored 18 out of 20 in Quiz A. Alex scored 40 out of 50 in Quiz B. Who did better?": "/assets/audio/w6_q1_prompt.mp3",
  "key:w6_q1_prompt": "/assets/audio/w6_q1_prompt.mp3",
  "The totals are different, so turn each score into a percent: divide the score by the total, then multiply by 100.": "/assets/audio/w6_q1_hint.mp3",
  "key:w6_q1_hint": "/assets/audio/w6_q1_hint.mp3",
  "Ravi made 33 of 40 free throws. Mia made 21 of 25 free throws. Who has the better shooting record?": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q2_prompt": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q2_hint": "/assets/audio/w6_q1_hint.mp3",
  "Team Red won 9 of 12 games. Team Blue won 32 of 40 games. Which team has the better winning record?": "/assets/audio/w6_q3_prompt.mp3",
  "key:w6_q3_prompt": "/assets/audio/w6_q3_prompt.mp3",
  "key:w6_q3_hint": "/assets/audio/w6_q1_hint.mp3",
  "Leo solved 44 of 50 puzzles. Zara solved 27 of 30 puzzles. Who solved the greater percent?": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q4_prompt": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q4_hint": "/assets/audio/w6_q1_hint.mp3",
  "Nina got 15 out of 25 in a maths test. Omar got 21 out of 35 in a science test. Who did better?": "/assets/audio/w6_q5_prompt.mp3",
  "key:w6_q5_prompt": "/assets/audio/w6_q5_prompt.mp3",
  "key:w6_q5_hint": "/assets/audio/w6_q1_hint.mp3",
  "Batch 1 had 13 good loaves out of 20. Batch 2 had 32 good loaves out of 50. Which batch had the higher success rate?": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q6_prompt": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q6_hint": "/assets/audio/w6_q1_hint.mp3",
  "Lena scored 13 out of 25 in a reading test. Kai scored 22 out of 40 in a spelling test. Who did better?": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q7_prompt": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q7_hint": "/assets/audio/w6_q1_hint.mp3",
  "Ava got 36 out of 40 in a science quiz. What percent did Ava score?": "/assets/audio/w6_q8_prompt.mp3",
  "key:w6_q8_prompt": "/assets/audio/w6_q8_prompt.mp3",
  "Divide the score by the total, then multiply by 100.": "/assets/audio/w6_q8_hint.mp3",
  "key:w6_q8_hint": "/assets/audio/w6_q8_hint.mp3",
  "Ben got 17 out of 20 on Quiz 1 and 21 out of 25 on Quiz 2. Which quiz did Ben do better on?": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_prompt": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_hint": "/assets/audio/w6_q1_hint.mp3",
  "Sam hit 14 of 16 targets. Tia hit 22 of 25 targets. Who was more accurate?": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_prompt": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_hint": "/assets/audio/w6_q1_hint.mp3",
  "What is 10% of 250?": "/assets/audio/w7_q1_prompt.mp3",
  "key:w7_q1_prompt": "/assets/audio/w7_q1_prompt.mp3",
  "Ten percent means one tenth. Divide 250 by 10.": "/assets/audio/w7_q1_hint.mp3",
  "key:w7_q1_hint": "/assets/audio/w7_q1_hint.mp3",
  "What is 25% of 80?": "/assets/audio/w7_q2_prompt.mp3",
  "key:w7_q2_prompt": "/assets/audio/w7_q2_prompt.mp3",
  "Twenty five percent is one quarter. Divide 80 by 4.": "/assets/audio/w7_q2_hint.mp3",
  "key:w7_q2_hint": "/assets/audio/w7_q2_hint.mp3",
  "A jar has 64 marbles. 50% of them are blue. How many are blue?": "/assets/audio/w7_q3_prompt.mp3",
  "key:w7_q3_prompt": "/assets/audio/w7_q3_prompt.mp3",
  "Fifty percent is one half. Divide 64 by 2.": "/assets/audio/w7_q3_hint.mp3",
  "key:w7_q3_hint": "/assets/audio/w7_q3_hint.mp3",
  "What is 20% of 150?": "/assets/audio/w7_q4_prompt.mp3",
  "key:w7_q4_prompt": "/assets/audio/w7_q4_prompt.mp3",
  "Find 10% first by dividing 150 by 10, then scale up to 20%.": "/assets/audio/w7_q4_hint.mp3",
  "key:w7_q4_hint": "/assets/audio/w7_q4_hint.mp3",
  "A school has 200 students. 5% are absent today. How many are absent?": "/assets/audio/w7_q5_prompt.mp3",
  "key:w7_q5_prompt": "/assets/audio/w7_q5_prompt.mp3",
  "Find 10% first (20), then halve it to get 5%.": "/assets/audio/w7_q5_hint.mp3",
  "key:w7_q5_hint": "/assets/audio/w7_q5_hint.mp3",
  "What is 75% of 60?": "/assets/audio/w7_q6_prompt.mp3",
  "key:w7_q6_prompt": "/assets/audio/w7_q6_prompt.mp3",
  "Seventy five percent is three quarters. Find one quarter of 60, then multiply by 3.": "/assets/audio/w7_q6_hint.mp3",
  "key:w7_q6_hint": "/assets/audio/w7_q6_hint.mp3",
  "What is 30% of 90?": "/assets/audio/w7_q7_prompt.mp3",
  "key:w7_q7_prompt": "/assets/audio/w7_q7_prompt.mp3",
  "Find 10% of 90, then multiply by 3.": "/assets/audio/w7_q7_hint.mp3",
  "key:w7_q7_hint": "/assets/audio/w7_q7_hint.mp3",
  "A team played 40 matches and won 15% of them. How many matches did they win?": "/assets/audio/w7_q8_prompt.mp3",
  "key:w7_q8_prompt": "/assets/audio/w7_q8_prompt.mp3",
  "Find 10% (4) and 5% (2), then add them.": "/assets/audio/w7_q8_hint.mp3",
  "key:w7_q8_hint": "/assets/audio/w7_q8_hint.mp3",
  "What is 60% of 45?": "/assets/audio/w7_q9_prompt.mp3",
  "key:w7_q9_prompt": "/assets/audio/w7_q9_prompt.mp3",
  "Find 10% first by dividing 45 by 10, then scale up to 60%.": "/assets/audio/w7_q9_hint.mp3",
  "key:w7_q9_hint": "/assets/audio/w7_q9_hint.mp3",
  "A jacket costs $120. The tax is 35% of that price. How much is the tax?": "/assets/audio/w7_q10_prompt.mp3",
  "key:w7_q10_prompt": "/assets/audio/w7_q10_prompt.mp3",
  "Find 10% (12), then 30% and 5%, and add them.": "/assets/audio/w7_q10_hint.mp3",
  "key:w7_q10_hint": "/assets/audio/w7_q10_hint.mp3",
  "Which is more: 50% of 20 or 30% of 80?": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q1_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "The wholes are different, so a bigger percent may not mean a bigger amount. Find each amount first.": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q1_hint": "/assets/audio/w8_q1_hint.mp3",
  "School A has 400 students and 30% walk. School B has 250 students and 44% walk. Which school has more walkers?": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_prompt": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which is more: 60% of 50 or 45% of 80?": "/assets/audio/w8_q3_prompt.mp3",
  "key:w8_q3_prompt": "/assets/audio/w8_q3_prompt.mp3",
  "key:w8_q3_hint": "/assets/audio/w8_q1_hint.mp3",
  "Tank 1 holds 80 litres and is 75% full. Tank 2 holds 120 litres and is 55% full. Which tank has more water?": "/assets/audio/w8_q4_prompt.mp3",
  "key:w8_q4_prompt": "/assets/audio/w8_q4_prompt.mp3",
  "key:w8_q4_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which is more: 20% of 300 or 35% of 160?": "/assets/audio/w8_q5_prompt.mp3",
  "key:w8_q5_prompt": "/assets/audio/w8_q5_prompt.mp3",
  "key:w8_q5_hint": "/assets/audio/w8_q1_hint.mp3",
  "Class 7A has 40 students and 65% are girls. Class 7B has 32 students and 75% are girls. Which class has more girls?": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_prompt": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_hint": "/assets/audio/w8_q1_hint.mp3",
  "Battery A holds 3000 units of charge and is 40% full. Battery B holds 4500 units and is 30% full. Which battery has more charge left?": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_prompt": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which is more: 12% of 500 or 15% of 350?": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_prompt": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_hint": "/assets/audio/w8_q1_hint.mp3",
  "Farm P plants corn on 35% of its 200 acres. Farm Q plants corn on 50% of its 120 acres. Which farm has more corn land?": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_prompt": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_hint": "/assets/audio/w8_q1_hint.mp3",
  "Which is more: 8% of 900 or 15% of 500?": "/assets/audio/w8_q10_prompt.mp3",
  "key:w8_q10_prompt": "/assets/audio/w8_q10_prompt.mp3",
  "key:w8_q10_hint": "/assets/audio/w8_q1_hint.mp3",
  "Shop A gives 25% off a $60 pair of sneakers. Shop B gives 10% off a $200 backpack. Which shop saves you more money?": "/assets/audio/w9_q1_prompt.mp3",
  "key:w9_q1_prompt": "/assets/audio/w9_q1_prompt.mp3",
  "A bigger percent off is not always a bigger saving. Find how many dollars each shop saves you.": "/assets/audio/w9_q1_hint.mp3",
  "key:w9_q1_hint": "/assets/audio/w9_q1_hint.mp3",
  "Shop A gives 30% off $90 headphones. Shop B gives 50% off a $50 speaker. Which shop saves you more money?": "/assets/audio/w9_q2_prompt.mp3",
  "key:w9_q2_prompt": "/assets/audio/w9_q2_prompt.mp3",
  "key:w9_q2_hint": "/assets/audio/w9_q1_hint.mp3",
  "Shop A gives 10% off a $200 jacket. Shop B gives 25% off an $80 board game. Which shop saves you more money?": "/assets/audio/w9_q3_prompt.mp3",
  "key:w9_q3_prompt": "/assets/audio/w9_q3_prompt.mp3",
  "key:w9_q3_hint": "/assets/audio/w9_q1_hint.mp3",
  "Shop A gives 15% off a $150 lamp. Shop B gives 40% off a $70 book set. Which shop saves you more money?": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q4_prompt": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q4_hint": "/assets/audio/w9_q1_hint.mp3",
  "Shop A gives 40% off an $80 helmet. Shop B gives 10% off a $300 bike. Which shop saves you more money?": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_prompt": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_hint": "/assets/audio/w9_q1_hint.mp3",
  "A video game costs $80. It is on sale for 25% off. What is the sale price?": "/assets/audio/w9_q6_prompt.mp3",
  "key:w9_q6_prompt": "/assets/audio/w9_q6_prompt.mp3",
  "First find 25% of $80. Then subtract that saving from the price.": "/assets/audio/w9_q6_hint.mp3",
  "key:w9_q6_hint": "/assets/audio/w9_q6_hint.mp3",
  "A bike helmet costs $120 and is 15% off. What is the sale price?": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q7_prompt": "/assets/audio/w9_q7_prompt.mp3",
  "First find 15% of $120. Then subtract that saving from the price.": "/assets/audio/w9_q7_hint.mp3",
  "key:w9_q7_hint": "/assets/audio/w9_q7_hint.mp3",
  "Shop A sells a $50 item at 20% off. Shop B sells a $45 item at 10% off. Which shop has the lower sale price?": "/assets/audio/w9_q8_prompt.mp3",
  "key:w9_q8_prompt": "/assets/audio/w9_q8_prompt.mp3",
  "Find the sale price of each item: price minus saving. The lower sale price is the better deal.": "/assets/audio/w9_q8_hint.mp3",
  "key:w9_q8_hint": "/assets/audio/w9_q8_hint.mp3",
  "Shop A sells a $200 scooter at 30% off. Shop B sells a $150 scooter at 10% off. Which shop has the lower sale price?": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q9_prompt": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q9_hint": "/assets/audio/w9_q8_hint.mp3",
  "Shop A gives 30% off a $75 coat. Shop B gives 25% off an $80 coat. Which shop saves you more money?": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q10_prompt": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q10_hint": "/assets/audio/w9_q1_hint.mp3",
  "A candidate had 48% of the votes last year and 55% this year. By how many percentage points did the vote share rise?": "/assets/audio/w10_q1_prompt.mp3",
  "key:w10_q1_prompt": "/assets/audio/w10_q1_prompt.mp3",
  "Both values are percents, so just subtract them. The gap is measured in percentage points.": "/assets/audio/w10_q1_hint.mp3",
  "key:w10_q1_hint": "/assets/audio/w10_q1_hint.mp3",
  "A game costs $40. Next month it costs $50. What is the percent increase in price?": "/assets/audio/w10_q2_prompt.mp3",
  "key:w10_q2_prompt": "/assets/audio/w10_q2_prompt.mp3",
  "Percent change = change ÷ ORIGINAL value × 100. Divide by the starting value, not the new one.": "/assets/audio/w10_q2_hint.mp3",
  "key:w10_q2_hint": "/assets/audio/w10_q2_hint.mp3",
  "A phone case costs $50. It goes on sale for $40. What is the percent decrease in price?": "/assets/audio/w10_q3_prompt.mp3",
  "key:w10_q3_prompt": "/assets/audio/w10_q3_prompt.mp3",
  "key:w10_q3_hint": "/assets/audio/w10_q2_hint.mp3",
  "Class attendance was 80% on Monday and 92% on Friday. By how many percentage points did it rise?": "/assets/audio/w10_q4_prompt.mp3",
  "key:w10_q4_prompt": "/assets/audio/w10_q4_prompt.mp3",
  "key:w10_q4_hint": "/assets/audio/w10_q1_hint.mp3",
  "Store A raises the price of a $40 toy by 10%. Store B raises the price of a $30 toy by 15%. Which store raises its price by more dollars?": "/assets/audio/w10_q5_prompt.mp3",
  "key:w10_q5_prompt": "/assets/audio/w10_q5_prompt.mp3",
  "Find 10% of 40 and 15% of 30 in dollars, then compare the two amounts.": "/assets/audio/w10_q5_hint.mp3",
  "key:w10_q5_hint": "/assets/audio/w10_q5_hint.mp3",
  "A concert had 200 tickets sold on day one and 250 on day two. What is the percent increase?": "/assets/audio/w10_q6_prompt.mp3",
  "key:w10_q6_prompt": "/assets/audio/w10_q6_prompt.mp3",
  "key:w10_q6_hint": "/assets/audio/w10_q2_hint.mp3",
  "Sam's savings grew from $80 to $100. Ella's grew from $150 to $180. Whose savings grew by the greater percent?": "/assets/audio/w10_q7_prompt.mp3",
  "key:w10_q7_prompt": "/assets/audio/w10_q7_prompt.mp3",
  "Work out the percent increase for each person: increase ÷ starting amount × 100.": "/assets/audio/w10_q7_hint.mp3",
  "key:w10_q7_hint": "/assets/audio/w10_q7_hint.mp3",
  "A town had 500 people. Now it has 450 people. What is the percent decrease?": "/assets/audio/w10_q8_prompt.mp3",
  "key:w10_q8_prompt": "/assets/audio/w10_q8_prompt.mp3",
  "key:w10_q8_hint": "/assets/audio/w10_q2_hint.mp3",
  "Support for a school plan rose from 40% to 50%. Which statement is correct?": "/assets/audio/w10_q9_prompt.mp3",
  "key:w10_q9_prompt": "/assets/audio/w10_q9_prompt.mp3",
  "Subtract to get percentage points. For percent increase, divide that gap by the starting 40%.": "/assets/audio/w10_q9_hint.mp3",
  "key:w10_q9_hint": "/assets/audio/w10_q9_hint.mp3",
  "Battery A dropped from 80% to 60%. Battery B dropped from 50% to 40%. Which battery lost the greater percent of its OWN starting charge?": "/assets/audio/w10_q10_prompt.mp3",
  "key:w10_q10_prompt": "/assets/audio/w10_q10_prompt.mp3",
  "Find each drop as a percent of its own starting charge: drop ÷ start × 100.": "/assets/audio/w10_q10_hint.mp3",
  "key:w10_q10_hint": "/assets/audio/w10_q10_hint.mp3"
};
export default audioMap;
